// car 1 6 11 16 21
// nature 2 7 12 17 22
// home 3 8 13 18 23
// city 4 9 14 19 24 
// animal 5 10 15 20 25 

export const data:{imageId: string; imageUrl: string; description: string; category: string; uploadedBy: { name: string; email: string; profilePicUrl: string; }; uploadDate: string; tags: string[]; }[] = [
  {
    imageId: "1534",
    imageUrl: "/assets/image-car1.png",
    description: "Dreamy Vintage Ride – A beautifully painted vintage car in soft watercolor hues, blending gentle blues and purples, with a misty background adding a nostalgic charm.",
    category: "Car",
    uploadedBy: {
      name: "John Doe",
      email: "john.doe@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2025-02-04",
    tags: ["sunset", "ocean", "nature"],
  },
  {
    imageId: "2654",
    imageUrl: "/assets/image-nature1.png",
    description: "A dense forest painted in soft watercolor greens, with morning mist gently rising, blending into the sky with delicate blue and gray tones.",
    category: "Nature",
    uploadedBy: {
      name: "Jane Smith",
      email: "jane.smith@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2025-02-01",
    tags: ["mountains", "landscape", "nature"],
  },
  {
    imageId: "3895",
    imageUrl: "/assets/image-home1.png",
    description: "A charming countryside cottage with a thatched roof, surrounded by vibrant flowers and lush greenery, painted in soft pastel watercolor tones.",
    category: "Home",
    uploadedBy: {
      name: "Mike Johnson",
      email: "mike.johnson@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2025-01-28",
    tags: ["city", "night", "lights"],
  },
  {
    imageId: "4243",
    imageUrl: "/assets/image-city1.png",
    description: "A bustling urban street at dusk, with reflections of neon lights shimmering on wet pavement, painted in dreamy blues, purples, and warm oranges.",
    category: "City",
    uploadedBy: {
      name: "Emily Davis",
      email: "emily.davis@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2025-01-22",
    tags: ["forest", "trees", "path"],
  },
  {
    imageId: "5567",
    imageUrl: "/assets/image-animal1.png",
    description: "A beautifully painted wolf standing on a hill, howling at the full moon, with soft watercolor blends of deep blues, purples, and misty whites.",
    category: "Animal",
    uploadedBy: {
      name: "Alex Brown",
      email: "alex.brown@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2025-01-18",
    tags: ["butterfly", "flower", "wildlife"],
  },
  {
    imageId: "5761",
    imageUrl: "/assets/image-nature10.png",
    description: "A beautifully painted wolf standing on a hill, howling at the full moon, with soft watercolor blends of deep blues, purples, and misty whites.",
    category: "Nature",
    uploadedBy: {
      name: "Alex Brown",
      email: "alex.brown@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2025-01-18",
    tags: ["butterfly", "flower", "wildlife"],
  },
  {
    imageId: "6235",
    imageUrl: "/assets/image-car2.png",
    description: " A sleek modern car reflecting streetlights on a rainy evening, captured in fluid watercolor strokes, merging blues, grays, and soft yellows.",
    category: "Car",
    uploadedBy: {
      name: "Sara Wilson",
      email: "sara.wilson@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2025-01-15",
    tags: ["castle", "lake", "architecture"],
  },
  {
    imageId: "7875",
    imageUrl: "/assets/image-nature2.png",
    description: " A peaceful autumn landscape with trees glowing in shades of orange, red, and yellow, reflected in a calm lake, capturing the warmth of fall in soft brushstrokes.",
    category: "Nature",
    uploadedBy: {
      name: "David Miller",
      email: "david.miller@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2025-01-10",
    tags: ["market", "culture", "stalls"],
  },
  {
    imageId: "8567",
    imageUrl: "/assets/image-home2.png",
    description:
      "A rustic wooden cabin nestled in a snowy forest, with warm golden lights glowing through the windows, blending soft blues and whites with hints of warm orange.",
    category: "Home",
    uploadedBy: {
      name: "Laura Garcia",
      email: "laura.garcia@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2025-01-05",
    tags: ["wheat", "field", "golden"],
  },
  {
    imageId: "9879",
    imageUrl: "/assets/image-city2.png",
    description: " A vibrant city skyline bathed in the soft glow of a rising sun, with watercolor hues blending warm yellows, oranges, and soft pinks over towering buildings.",
    category: "City",
    uploadedBy: {
      name: "Tom White",
      email: "tom.white@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-30",
    tags: ["portrait", "smile", "elderly"],
  },
  {
    imageId: "9989",
    imageUrl: "/assets/image-car4.png",
    description: " A vibrant city skyline bathed in the soft glow of a rising sun, with watercolor hues blending warm yellows, oranges, and soft pinks over towering buildings.",
    category: "Car",
    uploadedBy: {
      name: "Tom White",
      email: "tom.white@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-30",
    tags: ["portrait", "smile", "elderly"],
  },
  {
    imageId: "1340",
    imageUrl: "/assets/image-animal2.png",
    description: "A gentle deer standing in a serene woodland, surrounded by tall trees with golden sunlight filtering through, painted in warm earthy watercolor tones.",
    category: "Animal",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "1111",
    imageUrl: "/assets/image-food1.png",
    description: "A gentle deer standing in a serene woodland, surrounded by tall trees with golden sunlight filtering through, painted in warm earthy watercolor tones.",
    category: "Food",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "1342",
    imageUrl: "/assets/image-car3.png",
    description: "A convertible car cruising along a coastal road, bathed in warm watercolor shades of orange, pink, and deep blue, evoking a peaceful evening journey.",
    category: "Car",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "1348",
    imageUrl: "/assets/image-nature3.png",
    description: "Rolling green hills fading into the horizon, bathed in warm watercolor hues of pink, orange, and purple, with a soft golden glow highlighting the scenery.",
    category: "Nature",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "5348",
    imageUrl: "/assets/image-nature7.png",
    description: "Rolling green hills fading into the horizon, bathed in warm watercolor hues of pink, orange, and purple, with a soft golden glow highlighting the scenery.",
    category: "Nature",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "2900",
    imageUrl: "/assets/image-home3.png",
    description: " A beautiful lakeside home reflecting the golden hues of the sunset, surrounded by trees with gentle ripples in the water, painted in soft watercolor strokes.",
    category: "Home",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "2800",
    imageUrl: "/assets/image-food2.png",
    description: " A beautiful lakeside home reflecting the golden hues of the sunset, surrounded by trees with gentle ripples in the water, painted in soft watercolor strokes.",
    category: "Food",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "9766",
    imageUrl: "/assets/image-city3.png",
    description: "A lively cityscape with glowing streetlights, moving cars, and towering skyscrapers, painted in deep blues, purples, and flickering neon lights.",
    category: "City",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "9796",
    imageUrl: "/assets/image-sport1.png",
    description: "A lively cityscape with glowing streetlights, moving cars, and towering skyscrapers, painted in deep blues, purples, and flickering neon lights.",
    category: "Sport",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "7547",
    imageUrl: "/assets/image-animal3.png",
    description: "Two dolphins leaping through crystal-clear blue waters, with splashes of watercolor blending shades of turquoise, deep blue, and soft white foam.",
    category: "Animal",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "9769",
    imageUrl: "/assets/image-nature4.png",
    description: "A delicate watercolor painting of cherry blossoms in full bloom, with petals drifting in the wind against a pastel blue sky, evoking the beauty of spring.",
    category: "Nature",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "9869",
    imageUrl: "/assets/image-nature8.png",
    description: "A delicate watercolor painting of cherry blossoms in full bloom, with petals drifting in the wind against a pastel blue sky, evoking the beauty of spring.",
    category: "Nature",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "9169",
    imageUrl: "/assets/image-sport2.png",
    description: "A delicate watercolor painting of cherry blossoms in full bloom, with petals drifting in the wind against a pastel blue sky, evoking the beauty of spring.",
    category: "Sport",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "3456",
    imageUrl: "/assets/image-home4.png",
    description: "A classic suburban house with a white picket fence, blooming gardens, and a bright blue sky, created with delicate brushwork in warm and cheerful colors.",
    category: "Home",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "9876",
    imageUrl: "/assets/image-city4.png",
    description: " A picturesque European-style street with cobblestone pathways, colorful historic buildings, and cozy cafes, created with delicate watercolor brushstrokes in earthy tones.",
    category: "City",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "7654",
    imageUrl: "/assets/image-animal4.png",
    description: " A strikingly colorful parrot perched on a branch, its feathers blending into a vivid mix of red, blue, yellow, and green, painted with expressive watercolor strokes.",
    category: "Animal",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "7234",
    imageUrl: "/assets/image-car5.png",
    description: "A watercolor-painted cityscape with a car in the foreground, reflecting neon lights in shades of purple, teal, and magenta, creating a dreamy, futuristic vibe.",
    category: "Car",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "3234",
    imageUrl: "/assets/image-sport3.png",
    description: "A watercolor-painted cityscape with a car in the foreground, reflecting neon lights in shades of purple, teal, and magenta, creating a dreamy, futuristic vibe.",
    category: "Sport",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "2341",
    imageUrl: "/assets/image-nature5.png",
    description: "A flowing river surrounded by lush greenery, with soft reflections of trees and the sky, painted in smooth watercolor strokes of blue and green for a calming effect.",
    category: "Nature",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "2831",
    imageUrl: "/assets/image-nature9.png",
    description: "A flowing river surrounded by lush greenery, with soft reflections of trees and the sky, painted in smooth watercolor strokes of blue and green for a calming effect.",
    category: "Nature",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "2211",
    imageUrl: "/assets/image-animal5.png",
    description: "A flowing river surrounded by lush greenery, with soft reflections of trees and the sky, painted in smooth watercolor strokes of blue and green for a calming effect.",
    category: "Animal",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "2394",
    imageUrl: "/assets/image-home5.png",
    description: " A peaceful Mediterranean-style villa with white walls and blue rooftops, overlooking the sea, surrounded by colorful flowers, painted in soft, dreamy watercolor shades.",
    category: "Home",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "8764",
    imageUrl: "/assets/image-city5.png",
    description: " A modern city skyline partially veiled in misty clouds, with watercolor blending cool blues, grays, and soft whites to create a dreamy, ethereal atmosphere",
    category: "City",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "2367",
    imageUrl: "/assets/image-home6.png",
    description: " A modern city skyline partially veiled in misty clouds, with watercolor blending cool blues, grays, and soft whites to create a dreamy, ethereal atmosphere",
    category: "Home",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "2307",
    imageUrl: "/assets/image-sport4.png",
    description: " A modern city skyline partially veiled in misty clouds, with watercolor blending cool blues, grays, and soft whites to create a dreamy, ethereal atmosphere",
    category: "Sport",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "0984",
    imageUrl: "/assets/image-animal6.png",
    description: " A modern city skyline partially veiled in misty clouds, with watercolor blending cool blues, grays, and soft whites to create a dreamy, ethereal atmosphere",
    category: "Animal",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "2348",
    imageUrl: "/assets/image-nature6.png",
    description: " A modern city skyline partially veiled in misty clouds, with watercolor blending cool blues, grays, and soft whites to create a dreamy, ethereal atmosphere",
    category: "Nature",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "8658",
    imageUrl: "/assets/image-home7.png",
    description: " A modern city skyline partially veiled in misty clouds, with watercolor blending cool blues, grays, and soft whites to create a dreamy, ethereal atmosphere",
    category: "Home",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "9765",
    imageUrl: "/assets/image-animal8.png",
    description: " A modern city skyline partially veiled in misty clouds, with watercolor blending cool blues, grays, and soft whites to create a dreamy, ethereal atmosphere",
    category: "Animal",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "9725",
    imageUrl: "/assets/image-animal7.png",
    description: " A modern city skyline partially veiled in misty clouds, with watercolor blending cool blues, grays, and soft whites to create a dreamy, ethereal atmosphere",
    category: "Animal",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
  {
    imageId: "9215",
    imageUrl: "/assets/image11.png",
    description: " A modern city skyline partially veiled in misty clouds, with watercolor blending cool blues, grays, and soft whites to create a dreamy, ethereal atmosphere",
    category: "Sport",
    uploadedBy: {
      name: "Anna Moore",
      email: "anna.moore@example.com",
      profilePicUrl: "/assets/image.png",
    },
    uploadDate: "2024-12-25",
    tags: ["river", "valley", "aerial"],
  },
];
